version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              cmake \
              g++ \
              libopenblas-dev \
              liblapack-dev \
              libx11-dev \
              libjpeg-dev \
              libpng-dev \
              libfreetype6-dev \
              zlib1g-dev

      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install awsebcli

      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb init crm-app --platform python-3.11 --region $AWS_DEFAULT_REGION
            eb use crm-env
            eb deploy

workflows:
  deploy-workflow:
    jobs:
      - deploy
