version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/python:3.10 
    steps:
      - checkout

      # Cache pip dependencies to speed up builds
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install system dependencies for dlib
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              cmake \
              g++ \
              python3-dev \
              libopenblas-dev \
              liblapack-dev \
              libatlas-base-dev \
              libx11-dev \
              libjpeg-dev \
              libpng-dev \
              libfreetype6-dev \
              zlib1g-dev \
              libboost-all-dev
          no_output_timeout: 30m

      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
            pip install awsebcli
          no_output_timeout: 30m

      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb init crm-app --platform python-3.10 --region $AWS_DEFAULT_REGION
            eb use crm-env
            eb deploy
          no_output_timeout: 30m

workflows:
  deploy-workflow:
    jobs:
      - deploy
