version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11

jobs:
  deploy:
    executor: python-executor
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install awsebcli

      # Deploy to Elastic Beanstalk
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb init crm-app --platform python-3.11 --region $AWS_DEFAULT_REGION
            eb deploy crm-env --staged

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy
