"""add filet

Revision ID: 01e086151154
Revises: 67e835656f55
Create Date: 2025-04-28 07:20:28.383744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '01e086151154'
down_revision: Union[str, None] = '67e835656f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_task', 'task_file_image',
               existing_type=mysql.JSON(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_task', 'task_file_image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
