"""product_type gfddgfd

Revision ID: 05b9a4a56ab6
Revises: 1cf11863f0e8
Create Date: 2025-05-21 08:09:05.969344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '05b9a4a56ab6'
down_revision: Union[str, None] = '1cf11863f0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_task', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_task', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_task', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_task', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_task', 'updated_admin_emp_id')
    op.drop_column('employee_task', 'updated_by_type')
    op.drop_column('employee_task', 'admin_emp_id')
    op.drop_column('employee_task', 'created_by_type')
    # ### end Alembic commands ###
