"""all datetime22

Revision ID: 0abba1cf93e8
Revises: f6f765c85f47
Create Date: 2025-05-27 09:59:24.450467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abba1cf93e8'
down_revision: Union[str, None] = 'f6f765c85f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('dispatch_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_manager_order', 'dispatch_at')
    # ### end Alembic commands ###
