"""all  jsh

Revision ID: 0c2f96758d6e
Revises: 24762de44d88
Create Date: 2025-05-13 12:18:50.859850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0c2f96758d6e'
down_revision: Union[str, None] = '24762de44d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee_Tasks_Customer',
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Employee_Tasks_Customer')
    # ### end Alembic commands ###
