"""hold_re_remark

Revision ID: 0cf75dfd1d99
Revises: a6464bfe8f14
Create Date: 2025-05-13 08:02:35.031230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0cf75dfd1d99'
down_revision: Union[str, None] = 'a6464bfe8f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('hold_remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_manager_order', sa.Column('hold_re_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_manager_order', 'hold_re_status')
    op.drop_column('project_manager_order', 'hold_remark')
    # ### end Alembic commands ###
