"""kjhfdkjnhdfs

Revision ID: 13e90bd65e20
Revises: d0516f57f296
Create Date: 2025-05-21 12:04:52.683895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '13e90bd65e20'
down_revision: Union[str, None] = 'd0516f57f296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_manager_purchase', sa.Column('procure_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_manager_purchase', 'procure_status')
    # ### end Alembic commands ###
