"""CategoryCreate

Revision ID: 14fa9bf8ed4d
Revises: dab84db5a67a
Create Date: 2025-05-17 10:14:27.250126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '14fa9bf8ed4d'
down_revision: Union[str, None] = 'dab84db5a67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('category', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('category', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('category', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'updated_admin_emp_id')
    op.drop_column('category', 'updated_by_type')
    op.drop_column('category', 'admin_emp_id')
    op.drop_column('category', 'created_by_type')
    # ### end Alembic commands ###
