"""doc date

Revision ID: 155c359b0c44
Revises: abd12860cdba
Create Date: 2025-06-06 11:38:40.070404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '155c359b0c44'
down_revision: Union[str, None] = 'abd12860cdba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('production', sa.Column('production_engeneer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production', sa.Column('doc_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production', sa.Column('doc_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production', sa.Column('rec_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production', sa.Column('exp_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'exp_date')
    op.drop_column('production', 'rec_date')
    op.drop_column('production', 'doc_date')
    op.drop_column('production', 'doc_no')
    op.drop_column('production', 'production_engeneer')
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
