"""all final22

Revision ID: 1a08a45d628e
Revises: 9356c4603d39
Create Date: 2025-05-27 08:01:58.794157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1a08a45d628e'
down_revision: Union[str, None] = '9356c4603d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('challan_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_manager_order', sa.Column('eway_bill_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_manager_order', sa.Column('dispatch_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_manager_order', sa.Column('authorized_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_manager_order', 'authorized_img')
    op.drop_column('project_manager_order', 'dispatch_img')
    op.drop_column('project_manager_order', 'eway_bill_no')
    op.drop_column('project_manager_order', 'challan_date')
    # ### end Alembic commands ###
