"""jkvfjklfkjv5555

Revision ID: 1bdf053e14ec
Revises: f1b29bd0a82a
Create Date: 2025-05-20 08:17:59.244398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1bdf053e14ec'
down_revision: Union[str, None] = 'f1b29bd0a82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_vendor', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dispatch_vendor', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dispatch_vendor', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dispatch_vendor', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_vendor', 'updated_admin_emp_id')
    op.drop_column('dispatch_vendor', 'updated_by_type')
    op.drop_column('dispatch_vendor', 'admin_emp_id')
    op.drop_column('dispatch_vendor', 'created_by_type')
    # ### end Alembic commands ###
