"""type

Revision ID: 1cf11863f0e8
Revises: 02845189c295
Create Date: 2025-05-21 05:56:04.653162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1cf11863f0e8'
down_revision: Union[str, None] = '02845189c295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_product_employee', sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_product_employee', 'product_type')
    # ### end Alembic commands ###
