"""convert order status

Revision ID: 1d082ee9ab27
Revises: ee7df1cdba26
Create Date: 2025-05-05 12:01:26.894796

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d082ee9ab27'
down_revision: Union[str, None] = 'ee7df1cdba26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation', sa.Column('comver_order_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'comver_order_status')
    # ### end Alembic commands ###
