"""allowance

Revision ID: 1d27b1507ae2
Revises: 2deae552dedb
Create Date: 2025-06-12 06:29:52.293627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1d27b1507ae2'
down_revision: Union[str, None] = '2deae552dedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_add_employee', sa.Column('pan_card', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('house_rent_allowance', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('dearness_allowance', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('medical_allowance', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('special_allowance', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('bonus', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('telephone_reimbursement', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('fuel_reimbursement', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('admin_add_employee', 'house_rent_allowance_pdf')
    op.drop_column('admin_add_employee', 'pf')
    op.drop_column('admin_add_employee', 'house_rent_allowance_value')
    op.drop_column('admin_add_employee', 'medical_allowance_pdf')
    op.drop_column('admin_add_employee', 'medical_allowance_value')
    op.drop_column('admin_add_employee', 'dearness_allowance_enabled')
    op.drop_column('admin_add_employee', 'tds')
    op.drop_column('admin_add_employee', 'pt')
    op.drop_column('admin_add_employee', 'dearness_allowance_pdf')
    op.drop_column('admin_add_employee', 'dearness_allowance_value')
    op.drop_column('admin_add_employee', 'house_rent_allowance_enabled')
    op.drop_column('admin_add_employee', 'medical_allowance_enabled')
    op.add_column('employee_files', sa.Column('medical_file_path', sa.Text(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('employee_files', 'medical_file_path')
    op.add_column('admin_add_employee', sa.Column('medical_allowance_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('admin_add_employee', sa.Column('house_rent_allowance_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('admin_add_employee', sa.Column('dearness_allowance_value', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('admin_add_employee', sa.Column('dearness_allowance_pdf', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('admin_add_employee', sa.Column('pt', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('admin_add_employee', sa.Column('tds', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('admin_add_employee', sa.Column('dearness_allowance_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('admin_add_employee', sa.Column('medical_allowance_value', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('admin_add_employee', sa.Column('medical_allowance_pdf', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('admin_add_employee', sa.Column('house_rent_allowance_value', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('admin_add_employee', sa.Column('pf', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('admin_add_employee', sa.Column('house_rent_allowance_pdf', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('admin_add_employee', 'fuel_reimbursement')
    op.drop_column('admin_add_employee', 'telephone_reimbursement')
    op.drop_column('admin_add_employee', 'bonus')
    op.drop_column('admin_add_employee', 'special_allowance')
    op.drop_column('admin_add_employee', 'medical_allowance')
    op.drop_column('admin_add_employee', 'dearness_allowance')
    op.drop_column('admin_add_employee', 'house_rent_allowance')
    op.drop_column('admin_add_employee', 'pan_card')
    # ### end Alembic commands ###
