"""admin_assign_role

Revision ID: 22e0b93810d6
Revises: 846745731f6b
Create Date: 2025-05-23 07:57:08.858534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '22e0b93810d6'
down_revision: Union[str, None] = '846745731f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_assign_role_details',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('switched_role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_asign_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_assign_role_details')
    # ### end Alembic commands ###
