"""add template key store model

Revision ID: 2314e2592916
Revises: 3bca5d5a9c2b
Create Date: 2025-04-10 11:04:50.008762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2314e2592916'
down_revision: Union[str, None] = '3bca5d5a9c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_product_templates_key',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temp_key_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temp_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_product_templates_key')
    # ### end Alembic commands ###
