"""date_of_hold

Revision ID: 24762de44d88
Revises: 0cf75dfd1d99
Create Date: 2025-05-13 08:27:02.615564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '24762de44d88'
down_revision: Union[str, None] = '0cf75dfd1d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('date_of_hold', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('project_manager_order', 'hold_remark',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_manager_order', 'hold_remark',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('project_manager_order', 'date_of_hold')
    # ### end Alembic commands ###
