"""hiudfhufdfdjh

Revision ID: 25f7796aaa45
Revises: e37b4702a00a
Create Date: 2025-05-19 11:17:46.838742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '25f7796aaa45'
down_revision: Union[str, None] = 'e37b4702a00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_sales', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_sales', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_sales', 'updated_admin_emp_id')
    op.drop_column('admin_sales', 'updated_by_type')
    # ### end Alembic commands ###
