"""product grn add

Revision ID: 2d7fa81cfc21
Revises: 5222df0796d9
Create Date: 2025-06-16 07:55:29.622757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2d7fa81cfc21'
down_revision: Union[str, None] = '5222df0796d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('grn_order_product', sa.Column('accepted_qty_by_invoice', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('grn_order_product', sa.Column('rate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('grn_order_product', sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grn_order_product', 'amount')
    op.drop_column('grn_order_product', 'rate')
    op.drop_column('grn_order_product', 'accepted_qty_by_invoice')
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
