"""454545455454544

Revision ID: 2deae552dedb
Revises: 3847d6b5e3b1
Create Date: 2025-06-11 13:21:19.232002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '2deae552dedb'
down_revision: Union[str, None] = '3847d6b5e3b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_add_employee', sa.Column('medical_allowance_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('medical_allowance_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('medical_allowance_enabled', sa.Boolean(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('admin_add_employee', 'medical_allowance_enabled')
    op.drop_column('admin_add_employee', 'medical_allowance_pdf')
    op.drop_column('admin_add_employee', 'medical_allowance_value')
    # ### end Alembic commands ###
