"""add multy

Revision ID: 2f82e9580a75
Revises: efb0fb9d0ffb
Create Date: 2025-05-16 11:17:15.713363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2f82e9580a75'
down_revision: Union[str, None] = 'efb0fb9d0ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_manager_product', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('store_manager_product', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendor', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendor', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendor', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendor', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'updated_admin_emp_id')
    op.drop_column('vendor', 'updated_by_type')
    op.drop_column('vendor', 'admin_emp_id')
    op.drop_column('vendor', 'created_by_type')
    op.drop_column('store_manager_product', 'updated_admin_emp_id')
    op.drop_column('store_manager_product', 'updated_by_type')
    # ### end Alembic commands ###
