"""add parent

Revision ID: 324d692832d7
Revises: e2b9bb1b75c3
Create Date: 2025-04-22 07:33:09.271375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '324d692832d7'
down_revision: Union[str, None] = 'e2b9bb1b75c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stages', sa.Column('parent_stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_stages', 'parent_stage_id')
    # ### end Alembic commands ###
