"""jfodsflfd5656

Revision ID: 379ec3417a49
Revises: b6394c064d79
Create Date: 2025-05-17 12:41:34.524407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '379ec3417a49'
down_revision: Union[str, None] = 'b6394c064d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_template', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation_template', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_template', 'updated_admin_emp_id')
    op.drop_column('quotation_template', 'updated_by_type')
    # ### end Alembic commands ###
