"""dearness_allowance212121

Revision ID: 3847d6b5e3b1
Revises: 7cad39860490
Create Date: 2025-06-11 12:55:52.030993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '3847d6b5e3b1'
down_revision: Union[str, None] = '7cad39860490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_add_employee', sa.Column('house_rent_allowance_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('dearness_allowance_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('admin_add_employee', 'dearness_allowance_pdf')
    op.drop_column('admin_add_employee', 'house_rent_allowance_pdf')
    # ### end Alembic commands ###
