"""purchase order product

Revision ID: 3bca5d5a9c2b
Revises: dd0b3f605ae6
Create Date: 2025-04-10 04:46:27.912333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bca5d5a9c2b'
down_revision: Union[str, None] = 'dd0b3f605ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_assign_by_level')
    op.alter_column('purchase_order_issue', 'order_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_order_issue', 'expiry_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_order_issue', 'order_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('purchase_order_issue', 'frieght_mode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order_issue', 'frieght_mode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchase_order_issue', 'order_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchase_order_issue', 'expiry_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('purchase_order_issue', 'order_date',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_table('role_assign_by_level',
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employe_id_from', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('employe_id_to', mysql.JSON(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
