"""fin

Revision ID: 3c5735403b35
Revises: ee668c6a0b51
Create Date: 2025-06-23 13:11:47.573356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c5735403b35'
down_revision: Union[str, None] = 'ee668c6a0b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('dispatch_dashboard_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('dispatch_dashboard_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('dispatch_dashboard_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('dispatch_dashboard_delete', sa.Integer(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('admin_role_creation', 'dispatch_dashboard_delete')
    op.drop_column('admin_role_creation', 'dispatch_dashboard_edit')
    op.drop_column('admin_role_creation', 'dispatch_dashboard_write')
    op.drop_column('admin_role_creation', 'dispatch_dashboard_read')
    # ### end Alembic commands ###
