"""eway

Revision ID: 3ebe12e737f9
Revises: 8fea5cd0ade0
Create Date: 2025-05-07 12:45:13.523338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ebe12e737f9'
down_revision: Union[str, None] = '8fea5cd0ade0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_outward', sa.Column('challan_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('eway_bill_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_outward', 'eway_bill_no')
    op.drop_column('inventory_outward', 'challan_date')
    # ### end Alembic commands ###
