"""all fvxdfvdxv9897456546456

Revision ID: 42f402eb7bf9
Revises: f96e8f6b6595
Create Date: 2025-05-28 11:15:04.459687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '42f402eb7bf9'
down_revision: Union[str, None] = 'f96e8f6b6595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('quotation', sa.Column('pi_series', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('po_series', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('dc_series', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('inv_series', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('quotation', 'discription',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('quotation', 'delevery_address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotation', 'delevery_address',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('quotation', 'discription',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('quotation', 'inv_series')
    op.drop_column('quotation', 'dc_series')
    op.drop_column('quotation', 'po_series')
    op.drop_column('quotation', 'pi_series')
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
