"""add FacebookLead

Revision ID: 4592711fc327
Revises: e7c2a1c90213
Create Date: 2025-04-18 08:13:11.692112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4592711fc327'
down_revision: Union[str, None] = 'e7c2a1c90213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FacebookLead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('leadgen_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('field_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FacebookLead')
    # ### end Alembic commands ###
