"""hfhsdhfsdproduct_data

Revision ID: 47e70b28478f
Revises: bc5de3d4ad37
Create Date: 2025-05-19 05:47:54.499452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '47e70b28478f'
down_revision: Union[str, None] = 'bc5de3d4ad37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_product', sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_product', 'employee_id')
    # ### end Alembic commands ###
