"""dispatch by

Revision ID: 49df62d3c4df
Revises: a4c784d15c0b
Create Date: 2025-05-27 08:28:43.653298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49df62d3c4df'
down_revision: Union[str, None] = 'a4c784d15c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('dispatch_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_manager_order', sa.Column('dispatch_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_manager_order', 'dispatch_admin_emp_id')
    op.drop_column('project_manager_order', 'dispatch_by_type')
    # ### end Alembic commands ###
