"""jkvfjklfkjv

Revision ID: 4b5eed9ebd34
Revises: 7b747ec5c36a
Create Date: 2025-05-20 06:09:55.113436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4b5eed9ebd34'
down_revision: Union[str, None] = '7b747ec5c36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('delivery_challan', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('delivery_challan', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('delivery_challan', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_challan', 'updated_admin_emp_id')
    op.drop_column('delivery_challan', 'updated_by_type')
    op.drop_column('delivery_challan', 'admin_emp_id')
    op.drop_column('delivery_challan', 'created_by_type')
    # ### end Alembic commands ###
