"""role update

Revision ID: 4b74e73d2f76
Revises: 5fe1f56f3b6d
Create Date: 2025-04-11 06:31:38.653214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b74e73d2f76'
down_revision: Union[str, None] = '5fe1f56f3b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('dispatch_current_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('dispatch_current_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('idispatch_current_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('dispatch_current_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role_creation', 'dispatch_current_delete')
    op.drop_column('admin_role_creation', 'idispatch_current_edit')
    op.drop_column('admin_role_creation', 'dispatch_current_write')
    op.drop_column('admin_role_creation', 'dispatch_current_read')
    # ### end Alembic commands ###
