"""lojh

Revision ID: 4c51ab28a889
Revises: 6cea2334a54c
Create Date: 2025-05-22 10:52:34.057604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4c51ab28a889'
down_revision: Union[str, None] = '6cea2334a54c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_manager_order', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_manager_order', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project_manager_order', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_manager_order', 'updated_admin_emp_id')
    op.drop_column('project_manager_order', 'updated_by_type')
    op.drop_column('project_manager_order', 'admin_emp_id')
    op.drop_column('project_manager_order', 'created_by_type')
    # ### end Alembic commands ###
