"""updated_by_type

Revision ID: 506140f273a5
Revises: 2cb9a5314b5c
Create Date: 2025-06-19 06:43:53.914366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '506140f273a5'
down_revision: Union[str, None] = '2cb9a5314b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StoreCheckPoint', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('created_by_date', sa.DateTime(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('updated_by_date', sa.DateTime(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('StoreCheckPoint', 'updated_by_date')
    op.drop_column('StoreCheckPoint', 'updated_admin_emp_id')
    op.drop_column('StoreCheckPoint', 'updated_by_type')
    op.drop_column('StoreCheckPoint', 'created_by_date')
    op.drop_column('StoreCheckPoint', 'admin_emp_id')
    op.drop_column('StoreCheckPoint', 'created_by_type')
    # ### end Alembic commands ###
