"""add multy333

Revision ID: 5773627ddf30
Revises: 2f82e9580a75
Create Date: 2025-05-16 11:19:40.701698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5773627ddf30'
down_revision: Union[str, None] = '2f82e9580a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_template', sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation_template', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation_template', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_template', 'created_by_type')
    op.drop_column('quotation_template', 'admin_emp_id')
    op.drop_column('quotation_template', 'employee_id')
    # ### end Alembic commands ###
