"""add True

Revision ID: 5a62c9f581e6
Revises: 5f4d34092319
Create Date: 2025-04-17 09:27:03.833220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a62c9f581e6'
down_revision: Union[str, None] = '5f4d34092319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('employee_files', 'file_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'file_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
