"""fgfbcb

Revision ID: 5b6761986c31
Revises: bf35626f7d53
Create Date: 2025-05-22 12:57:17.255914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6761986c31'
down_revision: Union[str, None] = 'bf35626f7d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('challan_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_manager_order', 'challan_status')
    # ### end Alembic commands ###
