"""all gffc

Revision ID: 5ca9536dd81a
Revises: 420ed15b631a
Create Date: 2025-05-28 05:50:17.572855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ca9536dd81a'
down_revision: Union[str, None] = '420ed15b631a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
