"""add remark

Revision ID: 5fe1f56f3b6d
Revises: 2314e2592916
Create Date: 2025-04-10 13:13:35.407313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5fe1f56f3b6d'
down_revision: Union[str, None] = '2314e2592916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('add_remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'add_remark')
    # ### end Alembic commands ###
