"""reste add

Revision ID: 630c7bfb3f2f
Revises: b6d3605aa3ea
Create Date: 2025-04-16 10:41:51.893658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '630c7bfb3f2f'
down_revision: Union[str, None] = 'b6d3605aa3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_add_employee', sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('super_admin_user_add_new_form', sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('super_admin_user_add_new_form', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_admin_user_add_new_form', 'reset_token_expiry')
    op.drop_column('super_admin_user_add_new_form', 'reset_token')
    op.drop_column('admin_add_employee', 'reset_token_expiry')
    op.drop_column('admin_add_employee', 'reset_token')
    # ### end Alembic commands ###
