"""Admin empd.full_name

Revision ID: 6569a54cb72f
Revises: 5773627ddf30
Create Date: 2025-05-16 13:08:50.408448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6569a54cb72f'
down_revision: Union[str, None] = '5773627ddf30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_steps', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product_steps', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product_steps', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product_steps', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_steps', 'updated_admin_emp_id')
    op.drop_column('product_steps', 'updated_by_type')
    op.drop_column('product_steps', 'admin_emp_id')
    op.drop_column('product_steps', 'created_by_type')
    # ### end Alembic commands ###
