"""statu pro32333

Revision ID: 6cea2334a54c
Revises: fa23a706b601
Create Date: 2025-05-21 12:47:04.327056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6cea2334a54c'
down_revision: Union[str, None] = 'fa23a706b601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('quotation', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'updated_admin_emp_id')
    op.drop_column('quotation', 'updated_by_type')
    # ### end Alembic commands ###
