"""add contact_person

Revision ID: 6d27fa98a433
Revises: 8bb304a53621
Create Date: 2025-05-01 09:58:26.353905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6d27fa98a433'
down_revision: Union[str, None] = '8bb304a53621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_issue', sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_issue', 'contact_person')
    # ### end Alembic commands ###
