"""contact_number

Revision ID: 6f9192bedeb3
Revises: 62b336601503
Create Date: 2025-05-26 07:44:49.864036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6f9192bedeb3'
down_revision: Union[str, None] = '62b336601503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_issue', sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_issue', 'contact_number')
    # ### end Alembic commands ###
