"""convert order status22

Revision ID: 719fadf8104d
Revises: 1d082ee9ab27
Create Date: 2025-05-05 12:03:05.719111

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719fadf8104d'
down_revision: Union[str, None] = '1d082ee9ab27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProjectManagerResourseFile', sa.Column('quotation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProjectManagerResourseFile', 'quotation_id')
    # ### end Alembic commands ###
