"""adddispatch

Revision ID: 743fd10039db
Revises: d88ac5c09eed
Create Date: 2025-05-06 06:42:36.872488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743fd10039db'
down_revision: Union[str, None] = 'd88ac5c09eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_product_employee', sa.Column('add_dispatch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_product_employee', 'add_dispatch')
    # ### end Alembic commands ###
