"""add requestbyteam

Revision ID: 77c7543253ba
Revises: b4aebf5a8454
Create Date: 2025-04-15 09:54:15.582177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c7543253ba'
down_revision: Union[str, None] = 'b4aebf5a8454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('inventory_requestbyteam_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('inventory_requestbyteam_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('inventory_requestbyteam_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('inventory_requestbyteam_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role_creation', 'inventory_requestbyteam_delete')
    op.drop_column('admin_role_creation', 'inventory_requestbyteam_edit')
    op.drop_column('admin_role_creation', 'inventory_requestbyteam_write')
    op.drop_column('admin_role_creation', 'inventory_requestbyteam_read')
    # ### end Alembic commands ###
