"""production

Revision ID: 79af949cdd4d
Revises: 743fd10039db
Create Date: 2025-05-06 06:47:21.646552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79af949cdd4d'
down_revision: Union[str, None] = '743fd10039db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('quotation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'quotation_id')
    # ### end Alembic commands ###
