"""rej

Revision ID: 7b747ec5c36a
Revises: 25f7796aaa45
Create Date: 2025-05-19 12:18:04.248672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7b747ec5c36a'
down_revision: Union[str, None] = '25f7796aaa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_leave', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_leave', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_leave', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_leave', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_leave', sa.Column('approve_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_leave', sa.Column('approve_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_leave', sa.Column('approve_updated_at', sa.DateTime(), nullable=True))
    op.add_column('employee_leave', sa.Column('rejacted_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_leave', sa.Column('rejacted_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_leave', sa.Column('rejacted_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_leave', 'rejacted_updated_at')
    op.drop_column('employee_leave', 'rejacted_admin_emp_id')
    op.drop_column('employee_leave', 'rejacted_by_type')
    op.drop_column('employee_leave', 'approve_updated_at')
    op.drop_column('employee_leave', 'approve_admin_emp_id')
    op.drop_column('employee_leave', 'approve_by_type')
    op.drop_column('employee_leave', 'updated_admin_emp_id')
    op.drop_column('employee_leave', 'updated_by_type')
    op.drop_column('employee_leave', 'admin_emp_id')
    op.drop_column('employee_leave', 'created_by_type')
    # ### end Alembic commands ###
