"""GrnOrderProduct

Revision ID: 7c1c424662c0
Revises: 1d27b1507ae2
Create Date: 2025-06-12 07:18:23.349982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '7c1c424662c0'
down_revision: Union[str, None] = '1d27b1507ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grn_order_issue',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grn_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('series_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grn_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor_chalan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_chalan_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grn_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grn_order_product',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grn_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recived_quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accepted_quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reject_quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_table('grn_order_product')
    op.drop_table('grn_order_issue')
    # ### end Alembic commands ###
