"""dearness_allowance

Revision ID: 7cad39860490
Revises: 1015a30107dc
Create Date: 2025-06-11 12:51:49.841959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '7cad39860490'
down_revision: Union[str, None] = '1015a30107dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_add_employee', sa.Column('house_rent_allowance_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('dearness_allowance_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('house_rent_allowance_enabled', sa.Boolean(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('dearness_allowance_enabled', sa.Boolean(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('pf', sa.Boolean(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('pt', sa.Boolean(), nullable=True))
    op.add_column('admin_add_employee', sa.Column('tds', sa.Boolean(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('admin_add_employee', 'tds')
    op.drop_column('admin_add_employee', 'pt')
    op.drop_column('admin_add_employee', 'pf')
    op.drop_column('admin_add_employee', 'dearness_allowance_enabled')
    op.drop_column('admin_add_employee', 'house_rent_allowance_enabled')
    op.drop_column('admin_add_employee', 'dearness_allowance_value')
    op.drop_column('admin_add_employee', 'house_rent_allowance_value')
    # ### end Alembic commands ###
