"""weekly_holidays

Revision ID: 7d36f5a4a5e0
Revises: 219ec6851d37
Create Date: 2025-06-10 12:14:56.253751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '7d36f5a4a5e0'
down_revision: Union[str, None] = '219ec6851d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('time_config', sa.Column('shift1_weekly_holidays', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('time_config', sa.Column('shift2_weekly_holidays', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('time_config', sa.Column('shift3_weekly_holidays', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_config', 'shift3_weekly_holidays')
    op.drop_column('time_config', 'shift2_weekly_holidays')
    op.drop_column('time_config', 'shift1_weekly_holidays')
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
