"""LargeBinary to re

Revision ID: 7eb6f55a0afa
Revises: c333b4e85acf
Create Date: 2025-05-15 12:04:34.634525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb6f55a0afa'
down_revision: Union[str, None] = 'c333b4e85acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('employee_files', 'file_path',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'file_path',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
