"""admin_assign_roleemp

Revision ID: 8af3ea79f94f
Revises: 22e0b93810d6
Create Date: 2025-05-23 08:14:35.679801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '8af3ea79f94f'
down_revision: Union[str, None] = '22e0b93810d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_assign_role', sa.Column('asign_employe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('admin_assign_role', 'employe_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_assign_role', 'employe_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('admin_assign_role', 'asign_employe_id')
    # ### end Alembic commands ###
