"""add type+created

Revision ID: 8bb304a53621
Revises: b723699b1802
Create Date: 2025-05-01 08:18:58.216154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8bb304a53621'
down_revision: Union[str, None] = 'b723699b1802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_manager_product', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('store_manager_product', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_manager_product', 'admin_emp_id')
    op.drop_column('store_manager_product', 'created_by_type')
    # ### end Alembic commands ###
