"""add booked_status

Revision ID: 8c19937b35df
Revises: 6d27fa98a433
Create Date: 2025-05-02 11:02:22.073457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8c19937b35df'
down_revision: Union[str, None] = '6d27fa98a433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_product_employee', sa.Column('booked_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_product_employee', 'booked_status')
    # ### end Alembic commands ###
