"""task_history_remark

Revision ID: 8f572537362f
Revises: 821b17e5cb96
Create Date: 2025-06-05 06:09:20.309359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '8f572537362f'
down_revision: Union[str, None] = '821b17e5cb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status_history',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emp_id_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_history_remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_table('task_status_history')
    # ### end Alembic commands ###
