"""pickimg

Revision ID: 8fea5cd0ade0
Revises: 00d87ee290d3
Create Date: 2025-05-06 12:39:37.708907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fea5cd0ade0'
down_revision: Union[str, None] = '00d87ee290d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_outward', sa.Column('authorized_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('dispatch_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_outward', 'dispatch_img')
    op.drop_column('inventory_outward', 'authorized_img')
    # ### end Alembic commands ###
