"""6666666

Revision ID: 904c5bc6f1b8
Revises: 6373a5b8eee4
Create Date: 2025-08-06 11:55:51.424718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '904c5bc6f1b8'
down_revision: Union[str, None] = '6373a5b8eee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('vendor', 'employe_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'vendor_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'contact_person',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'contact_gst_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'contact_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'pan_no',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'vendor_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'vendor_state',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'vendor_pin',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'account_holder_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'account_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor', 'ifsc_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor', 'ifsc_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'account_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'account_holder_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'vendor_pin',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'vendor_state',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'vendor_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'pan_no',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'contact_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'contact_gst_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'contact_person',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'vendor_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('vendor', 'employe_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
