"""all final

Revision ID: 9356c4603d39
Revises: 37337334b164
Create Date: 2025-05-27 07:14:39.826282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9356c4603d39'
down_revision: Union[str, None] = '37337334b164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_info', sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_info', 'order_id')
    # ### end Alembic commands ###
