"""book status

Revision ID: a4cf8f41a141
Revises: c9fb041223e2
Create Date: 2025-05-05 08:18:25.498200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a4cf8f41a141'
down_revision: Union[str, None] = 'c9fb041223e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_outward', sa.Column('book_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_outward', 'book_status')
    # ### end Alembic commands ###
