"""email add remark

Revision ID: a6464bfe8f14
Revises: adcf5b300ba7
Create Date: 2025-05-12 10:00:35.070229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a6464bfe8f14'
down_revision: Union[str, None] = 'adcf5b300ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_outward_remark',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emplpoyee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('InventoryOutward_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('add_remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('activity_center', 'activiity_message',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_center', 'activiity_message',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('inventory_outward_remark')
    # ### end Alembic commands ###
