"""Add fields in accounts22

Revision ID: aa047cbd7ce1
Revises: bf69551dc36f
Create Date: 2025-05-05 06:51:22.625730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'aa047cbd7ce1'
down_revision: Union[str, None] = 'bf69551dc36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('file_path2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('account', 'file_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'file_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('account', 'file_path2')
    # ### end Alembic commands ###
