"""sqlmodel dfd465656

Revision ID: ac3cca0b0c83
Revises: c38b8ebd1b37
Create Date: 2025-05-26 10:12:16.003227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ac3cca0b0c83'
down_revision: Union[str, None] = 'c38b8ebd1b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('super_admin_user_add_new_form', sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_admin_user_add_new_form', 'month')
    # ### end Alembic commands ###
