"""order_id_id

Revision ID: adaed4492a05
Revises: bdd3d38f4d97
Create Date: 2025-05-23 05:23:11.279498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adaed4492a05'
down_revision: Union[str, None] = 'bdd3d38f4d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_outward', sa.Column('dispatch_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('order_id_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_outward', 'order_id_id')
    op.drop_column('inventory_outward', 'dispatch_type')
    # ### end Alembic commands ###
