"""email contact_number

Revision ID: adcf5b300ba7
Revises: 3ebe12e737f9
Create Date: 2025-05-12 06:47:08.470065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'adcf5b300ba7'
down_revision: Union[str, None] = '3ebe12e737f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('contact_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('settings', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'email')
    op.drop_column('settings', 'contact_number')
    # ### end Alembic commands ###
