"""add stotr t,p,c 22 model

Revision ID: aef38656676f
Revises: 39aa873ffeb6
Create Date: 2025-04-09 12:28:52.397993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aef38656676f'
down_revision: Union[str, None] = '39aa873ffeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StoreCheckPoint',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subproduct_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('check_point_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('check_point_status', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Store_sub_product_employee',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('add_remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_templates',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_templates')
    op.drop_table('Store_sub_product_employee')
    op.drop_table('StoreCheckPoint')
    # ### end Alembic commands ###
