"""add allocatedwork

Revision ID: afb4c2832367
Revises: 4592711fc327
Create Date: 2025-04-19 06:55:23.356490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb4c2832367'
down_revision: Union[str, None] = '4592711fc327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('project_manager_allocatedwork_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('project_manager_allocatedwork_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('project_manager_allocatedwork_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('project_manager_allocatedwork_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_attendance_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_attendance_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_attendance_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_attendance_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_roleassignment_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_roleassignment_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_roleassignment_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_roleassignment_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_rolecreation_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_rolecreation_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_rolecreation_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_rolecreation_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_task_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_task_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_task_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_task_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_leave_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_leave_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_leave_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('employee_leave_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_termandcondition_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_termandcondition_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_termandcondition_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_termandcondition_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_brochure_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_brochure_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_brochure_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_brochure_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_series_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_series_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_series_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_series_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_timeconfig_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_timeconfig_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_timeconfig_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_timeconfig_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role_creation', 'config_timeconfig_delete')
    op.drop_column('admin_role_creation', 'config_timeconfig_edit')
    op.drop_column('admin_role_creation', 'config_timeconfig_write')
    op.drop_column('admin_role_creation', 'config_timeconfig_read')
    op.drop_column('admin_role_creation', 'config_series_delete')
    op.drop_column('admin_role_creation', 'config_series_edit')
    op.drop_column('admin_role_creation', 'config_series_write')
    op.drop_column('admin_role_creation', 'config_series_read')
    op.drop_column('admin_role_creation', 'config_brochure_delete')
    op.drop_column('admin_role_creation', 'config_brochure_edit')
    op.drop_column('admin_role_creation', 'config_brochure_write')
    op.drop_column('admin_role_creation', 'config_brochure_read')
    op.drop_column('admin_role_creation', 'config_termandcondition_delete')
    op.drop_column('admin_role_creation', 'config_termandcondition_edit')
    op.drop_column('admin_role_creation', 'config_termandcondition_write')
    op.drop_column('admin_role_creation', 'config_termandcondition_read')
    op.drop_column('admin_role_creation', 'employee_leave_delete')
    op.drop_column('admin_role_creation', 'employee_leave_edit')
    op.drop_column('admin_role_creation', 'employee_leave_write')
    op.drop_column('admin_role_creation', 'employee_leave_read')
    op.drop_column('admin_role_creation', 'employee_task_delete')
    op.drop_column('admin_role_creation', 'employee_task_edit')
    op.drop_column('admin_role_creation', 'employee_task_write')
    op.drop_column('admin_role_creation', 'employee_task_read')
    op.drop_column('admin_role_creation', 'employee_rolecreation_delete')
    op.drop_column('admin_role_creation', 'employee_rolecreation_edit')
    op.drop_column('admin_role_creation', 'employee_rolecreation_write')
    op.drop_column('admin_role_creation', 'employee_rolecreation_read')
    op.drop_column('admin_role_creation', 'employee_roleassignment_delete')
    op.drop_column('admin_role_creation', 'employee_roleassignment_edit')
    op.drop_column('admin_role_creation', 'employee_roleassignment_write')
    op.drop_column('admin_role_creation', 'employee_roleassignment_read')
    op.drop_column('admin_role_creation', 'employee_attendance_delete')
    op.drop_column('admin_role_creation', 'employee_attendance_edit')
    op.drop_column('admin_role_creation', 'employee_attendance_write')
    op.drop_column('admin_role_creation', 'employee_attendance_read')
    op.drop_column('admin_role_creation', 'project_manager_allocatedwork_delete')
    op.drop_column('admin_role_creation', 'project_manager_allocatedwork_edit')
    op.drop_column('admin_role_creation', 'project_manager_allocatedwork_write')
    op.drop_column('admin_role_creation', 'project_manager_allocatedwork_read')
    # ### end Alembic commands ###
