"""add pr

Revision ID: b06644170040
Revises: 6e62dd9c6c0f
Create Date: 2025-04-24 05:22:54.178223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b06644170040'
down_revision: Union[str, None] = '6e62dd9c6c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StoreCheckPoint', sa.Column('production_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Store_sub_product_employee', sa.Column('production_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('store_templates', sa.Column('production_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_templates', 'production_id')
    op.drop_column('Store_sub_product_employee', 'production_id')
    op.drop_column('StoreCheckPoint', 'production_id')
    # ### end Alembic commands ###
