"""role dispatch transport edit

Revision ID: b4aebf5a8454
Revises: 5ab26fbff075
Create Date: 2025-04-11 07:08:39.785881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4aebf5a8454'
down_revision: Union[str, None] = '5ab26fbff075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('dispatch_transport_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('dispatch_current_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('task_manager_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('task_manager_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('task_manager_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('task_manager_delete', sa.Integer(), nullable=True))
    op.drop_column('admin_role_creation', 'idispatch_current_edit')
    op.drop_column('admin_role_creation', 'idispatch_transport_edit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('idispatch_transport_edit', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admin_role_creation', sa.Column('idispatch_current_edit', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('admin_role_creation', 'task_manager_delete')
    op.drop_column('admin_role_creation', 'task_manager_edit')
    op.drop_column('admin_role_creation', 'task_manager_write')
    op.drop_column('admin_role_creation', 'task_manager_read')
    op.drop_column('admin_role_creation', 'dispatch_current_edit')
    op.drop_column('admin_role_creation', 'dispatch_transport_edit')
    # ### end Alembic commands ###
