"""[200~over_time_remark~

Revision ID: b5ad6c231bbd
Revises: 595c69d9838e
Create Date: 2025-06-09 10:42:43.655630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b5ad6c231bbd'
down_revision: Union[str, None] = '595c69d9838e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_attendance', sa.Column('over_time_remark', sa.Text(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('employee_attendance', 'over_time_remark')
    # ### end Alembic commands ###
