"""quotemanager

Revision ID: b5d400470b35
Revises: 719fadf8104d
Create Date: 2025-05-06 06:05:00.567634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d400470b35'
down_revision: Union[str, None] = '719fadf8104d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('quotation_id', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_manager_order', 'quotation_id')
    # ### end Alembic commands ###
