"""jfodsflfd

Revision ID: b6394c064d79
Revises: 14fa9bf8ed4d
Create Date: 2025-05-17 11:37:33.358974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b6394c064d79'
down_revision: Union[str, None] = '14fa9bf8ed4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_request', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production_request', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production_request', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production_request', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_request', 'updated_admin_emp_id')
    op.drop_column('production_request', 'updated_by_type')
    op.drop_column('production_request', 'admin_emp_id')
    op.drop_column('production_request', 'created_by_type')
    # ### end Alembic commands ###
