"""all lololo

Revision ID: b945c8190196
Revises: 2be2aed070bd
Create Date: 2025-05-30 05:23:41.494559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b945c8190196'
down_revision: Union[str, None] = '2be2aed070bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'note',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('account', 'note',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
