"""hfhsdhfsd

Revision ID: bc5de3d4ad37
Revises: a3960552f034
Create Date: 2025-05-17 13:10:59.245919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bc5de3d4ad37'
down_revision: Union[str, None] = 'a3960552f034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('employe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role_creation', 'updated_admin_emp_id')
    op.drop_column('admin_role_creation', 'updated_by_type')
    op.drop_column('admin_role_creation', 'admin_emp_id')
    op.drop_column('admin_role_creation', 'created_by_type')
    op.drop_column('admin_role_creation', 'employe_id')
    # ### end Alembic commands ###
