"""hjhghf

Revision ID: bdd3d38f4d97
Revises: 5b6761986c31
Create Date: 2025-05-23 05:20:22.537365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bdd3d38f4d97'
down_revision: Union[str, None] = '5b6761986c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('super_admin_user_add_new_form', 'phone_number',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('super_admin_user_add_new_form', 'phone_number',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
