"""Grn Invoice

Revision ID: bde097102908
Revises: 29f7009d0903
Create Date: 2025-06-16 06:05:13.441564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bde097102908'
down_revision: Union[str, None] = '29f7009d0903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grn_invoice',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grn_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vender_invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_table('grn_invoice')
    # ### end Alembic commands ###
