"""FDSGV

Revision ID: bf35626f7d53
Revises: 4c51ab28a889
Create Date: 2025-05-22 11:52:17.607053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf35626f7d53'
down_revision: Union[str, None] = '4c51ab28a889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('chalan_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('delivery_challan', sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_challan', 'order_id')
    op.drop_column('delivery_challan', 'chalan_type')
    # ### end Alembic commands ###
