"""Add fields in accounts

Revision ID: bf69551dc36f
Revises: e6020334d70f
Create Date: 2025-05-05 06:47:52.510053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'bf69551dc36f'
down_revision: Union[str, None] = 'e6020334d70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('rcvd_amt', sa.Float(), nullable=True))
    op.add_column('account', sa.Column('sent_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('handover_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('payment_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('account_holder_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('ifsc_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('ac_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('gst', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('payment_method_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('cheque_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('cheque_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('cheque_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('upi_number_or_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('transaction_upi_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('upi_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('account', 'note',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('account', 'file_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'file_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('account', 'note',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('account', 'upi_image')
    op.drop_column('account', 'transaction_upi_id')
    op.drop_column('account', 'upi_number_or_id')
    op.drop_column('account', 'cheque_image')
    op.drop_column('account', 'cheque_date')
    op.drop_column('account', 'cheque_no')
    op.drop_column('account', 'payment_method_type')
    op.drop_column('account', 'gst')
    op.drop_column('account', 'ac_no')
    op.drop_column('account', 'ifsc_code')
    op.drop_column('account', 'branch_name')
    op.drop_column('account', 'account_holder_name')
    op.drop_column('account', 'bank_name')
    op.drop_column('account', 'payment_date')
    op.drop_column('account', 'handover_name')
    op.drop_column('account', 'sent_by')
    op.drop_column('account', 'rcvd_amt')
    # ### end Alembic commands ###
