"""sqlmodel dfd

Revision ID: c38b8ebd1b37
Revises: 6f9192bedeb3
Create Date: 2025-05-26 10:06:47.722268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c38b8ebd1b37'
down_revision: Union[str, None] = '6f9192bedeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('super_admin_subscription_plan_price', sa.Column('plan_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('super_admin_subscription_plan_price', 'plan_type')
    # ### end Alembic commands ###
