"""GrnOrderProductupd

Revision ID: c8a7aed913d0
Revises: 7c1c424662c0
Create Date: 2025-06-12 07:26:43.093479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'c8a7aed913d0'
down_revision: Union[str, None] = '7c1c424662c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('grn_order_issue', sa.Column('vendor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('grn_order_issue', sa.Column('invoice_chalan', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('grn_order_issue', 'invoice_id')
    op.drop_column('grn_order_issue', 'vendor_chalan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grn_order_issue', sa.Column('vendor_chalan', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('grn_order_issue', sa.Column('invoice_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('grn_order_issue', 'invoice_chalan')
    op.drop_column('grn_order_issue', 'vendor_id')
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
