"""check id8888

Revision ID: c8f8b3d8b0bf
Revises: c9c8c0ba6ef5
Create Date: 2025-06-06 13:19:40.750569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'c8f8b3d8b0bf'
down_revision: Union[str, None] = 'c9c8c0ba6ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StoreCheckPoint', sa.Column('check_remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('check_remark_date', sa.DateTime(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('check_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('check_admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('StoreCheckPoint', sa.Column('check_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.drop_column('production', 'check_emp_id')
    op.drop_column('production', 'check_remark_date')
    op.drop_column('production', 'check_remark')
    op.drop_column('production', 'check_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('check_status', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('production', sa.Column('check_remark', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('production', sa.Column('check_remark_date', mysql.DATETIME(), nullable=True))
    op.add_column('production', sa.Column('check_emp_id', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('StoreCheckPoint', 'check_status')
    op.drop_column('StoreCheckPoint', 'check_admin_id')
    op.drop_column('StoreCheckPoint', 'check_emp_id')
    op.drop_column('StoreCheckPoint', 'check_remark_date')
    op.drop_column('StoreCheckPoint', 'check_remark')
    # ### end Alembic commands ###
