"""check id 

Revision ID: c9c8c0ba6ef5
Revises: c409ca558997
Create Date: 2025-06-06 12:59:51.475358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'c9c8c0ba6ef5'
down_revision: Union[str, None] = 'c409ca558997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('production', sa.Column('check_remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production', sa.Column('check_remark_date', sa.DateTime(), nullable=True))
    op.add_column('production', sa.Column('check_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('production', sa.Column('check_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production', 'check_status')
    op.drop_column('production', 'check_emp_id')
    op.drop_column('production', 'check_remark_date')
    op.drop_column('production', 'check_remark')
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
