"""Add fields in accounts23

Revision ID: c9fb041223e2
Revises: aa047cbd7ce1
Create Date: 2025-05-05 06:58:17.817165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'c9fb041223e2'
down_revision: Union[str, None] = 'aa047cbd7ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('note2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('account', 'note',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'note',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('account', 'note2')
    # ### end Alembic commands ###
