"""all hhhak

Revision ID: cf580812ba50
Revises: 0c2f96758d6e
Create Date: 2025-05-13 12:21:57.389986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cf580812ba50'
down_revision: Union[str, None] = '0c2f96758d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_task', sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_task', 'customer_id')
    # ### end Alembic commands ###
