"""product_type gfddgfd456545

Revision ID: d0516f57f296
Revises: 05b9a4a56ab6
Create Date: 2025-05-21 08:10:39.074560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0516f57f296'
down_revision: Union[str, None] = '05b9a4a56ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_task', 'from_date_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('employee_task', 'to_date_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_task', 'to_date_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('employee_task', 'from_date_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
