"""rfq update

Revision ID: d060159cb7ae
Revises: da92448b010f
Create Date: 2025-06-30 06:30:13.225551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd060159cb7ae'
down_revision: Union[str, None] = 'da92448b010f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('rfq', sa.Column('req_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rfq', sa.Column('vendor_due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rfq', sa.Column('quotation_due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfq', 'quotation_due_date')
    op.drop_column('rfq', 'vendor_due_date')
    op.drop_column('rfq', 'req_date')
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
