"""admin_id11

Revision ID: d4f05a74fdd1
Revises: 7eb6f55a0afa
Create Date: 2025-05-16 05:09:10.274239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd4f05a74fdd1'
down_revision: Union[str, None] = '7eb6f55a0afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('late_mark', sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('late_mark', sa.Column('select_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('late_mark', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('late_mark', sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('late_mark', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('late_mark', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('late_mark', 'updated_at')
    op.drop_column('late_mark', 'created_at')
    op.drop_column('late_mark', 'config_id')
    op.drop_column('late_mark', 'content')
    op.drop_column('late_mark', 'select_type')
    op.drop_column('late_mark', 'admin_id')
    # ### end Alembic commands ###
