"""quotemanager1

Revision ID: d88ac5c09eed
Revises: b5d400470b35
Create Date: 2025-05-06 06:12:44.091270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd88ac5c09eed'
down_revision: Union[str, None] = 'b5d400470b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_manager_order', 'quotation_id',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_manager_order', 'quotation_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
