"""add selected_product_ids

Revision ID: d8ec781ecd1e
Revises: e96e136fd23f
Create Date: 2025-04-23 04:56:15.378879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd8ec781ecd1e'
down_revision: Union[str, None] = 'e96e136fd23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stages', sa.Column('selected_product_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_stages', 'selected_product_ids')
    # ### end Alembic commands ###
