"""all employee_id

Revision ID: d9ae3b697559
Revises: cad387e714ef
Create Date: 2025-06-02 12:54:37.193574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'd9ae3b697559'
down_revision: Union[str, None] = 'cad387e714ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assign_request_remark', sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_asssign_request', sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('employee_asssign_request', 'employee_id')
    op.drop_column('assign_request_remark', 'employee_id')
    # ### end Alembic commands ###
