"""add Challan status

Revision ID: da0dae0cafe7
Revises: 4c7e006f63f6
Create Date: 2025-05-03 07:21:45.137857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'da0dae0cafe7'
down_revision: Union[str, None] = '4c7e006f63f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan', sa.Column('inventryoutword_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('challan_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_outward', 'challan_status')
    op.drop_column('delivery_challan', 'inventryoutword_id')
    # ### end Alembic commands ###
