"""role

Revision ID: da92448b010f
Revises: e7fe8062bf03
Create Date: 2025-06-27 06:42:08.884404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da92448b010f'
down_revision: Union[str, None] = 'e7fe8062bf03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('admin_mobile_read', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_write', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_edit', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_delete', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_attendance_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_attendance_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_attendance_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_attendance_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_task_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_task_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_task_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_task_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_leave_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_leave_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_leave_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_leave_delete', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_lead_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_lead_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_lead_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('admin_mobile_lead_delete', sa.Integer(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('admin_role_creation', 'admin_mobile_lead_delete')
    op.drop_column('admin_role_creation', 'admin_mobile_lead_edit')
    op.drop_column('admin_role_creation', 'admin_mobile_lead_write')
    op.drop_column('admin_role_creation', 'admin_mobile_lead_read')
    op.drop_column('admin_role_creation', 'admin_mobile_leave_delete')
    op.drop_column('admin_role_creation', 'admin_mobile_leave_edit')
    op.drop_column('admin_role_creation', 'admin_mobile_leave_write')
    op.drop_column('admin_role_creation', 'admin_mobile_leave_read')
    op.drop_column('admin_role_creation', 'admin_mobile_task_delete')
    op.drop_column('admin_role_creation', 'admin_mobile_task_edit')
    op.drop_column('admin_role_creation', 'admin_mobile_task_write')
    op.drop_column('admin_role_creation', 'admin_mobile_task_read')
    op.drop_column('admin_role_creation', 'admin_mobile_attendance_delete')
    op.drop_column('admin_role_creation', 'admin_mobile_attendance_edit')
    op.drop_column('admin_role_creation', 'admin_mobile_attendance_write')
    op.drop_column('admin_role_creation', 'admin_mobile_attendance_read')
    op.drop_column('admin_role_creation', 'admin_mobile_delete')
    op.drop_column('admin_role_creation', 'admin_mobile_edit')
    op.drop_column('admin_role_creation', 'admin_mobile_write')
    op.drop_column('admin_role_creation', 'admin_mobile_read')
    # ### end Alembic commands ###
