"""update_data

Revision ID: dab84db5a67a
Revises: 6569a54cb72f
Create Date: 2025-05-17 07:14:55.948214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dab84db5a67a'
down_revision: Union[str, None] = '6569a54cb72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_items', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('step_items', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('step_items', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('step_items', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_items', 'updated_admin_emp_id')
    op.drop_column('step_items', 'updated_by_type')
    op.drop_column('step_items', 'admin_emp_id')
    op.drop_column('step_items', 'created_by_type')
    # ### end Alembic commands ###
