"""add Quotation_stages models

Revision ID: dd0b3f605ae6
Revises: aef38656676f
Create Date: 2025-04-09 12:43:12.254721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dd0b3f605ae6'
down_revision: Union[str, None] = 'aef38656676f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quotation_Product_Stages',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assign_employee', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('step_item', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assign_date_time', sa.DateTime(), nullable=True),
    sa.Column('previous_date_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('previous_employee', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_product_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Quotation_Product_Stages')
    # ### end Alembic commands ###
