"""23323132122

Revision ID: de97305d9faa
Revises: 904c5bc6f1b8
Create Date: 2025-08-06 12:44:48.164184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de97305d9faa'
down_revision: Union[str, None] = '904c5bc6f1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('store_manager_product', 'emplpoyee_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('store_manager_product', 'purchase_request_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('store_manager_product', 'gst_rate',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_manager_product', 'gst_rate',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('store_manager_product', 'purchase_request_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('store_manager_product', 'emplpoyee_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
