"""True dddd

Revision ID: e164eab0385f
Revises: cf580812ba50
Create Date: 2025-05-14 09:33:37.216830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e164eab0385f'
down_revision: Union[str, None] = 'cf580812ba50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('vendor', sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'business_name')
    op.drop_column('vendor', 'bank_name')
    # ### end Alembic commands ###
