"""add is_duplicate

Revision ID: e2b9bb1b75c3
Revises: ec52d1bea1bf
Create Date: 2025-04-22 06:40:32.156474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b9bb1b75c3'
down_revision: Union[str, None] = 'ec52d1bea1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_sales', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_sales', 'is_duplicate')
    # ### end Alembic commands ###
