"""jjj2222

Revision ID: e37b4702a00a
Revises: cc05011ac41c
Create Date: 2025-05-19 08:30:50.387766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e37b4702a00a'
down_revision: Union[str, None] = 'cc05011ac41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_attendance', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('employee_attendance', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_attendance', 'admin_emp_id')
    op.drop_column('employee_attendance', 'created_by_type')
    # ### end Alembic commands ###
