"""created_updated_data

Revision ID: e3d85683d92b
Revises: 47e70b28478f
Create Date: 2025-05-19 07:24:29.472180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e3d85683d92b'
down_revision: Union[str, None] = '47e70b28478f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_manager_purchase', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('store_manager_purchase', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('store_manager_purchase', sa.Column('updated_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('store_manager_purchase', sa.Column('updated_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_manager_purchase', 'updated_admin_emp_id')
    op.drop_column('store_manager_purchase', 'updated_by_type')
    op.drop_column('store_manager_purchase', 'admin_emp_id')
    op.drop_column('store_manager_purchase', 'created_by_type')
    # ### end Alembic commands ###
