"""dispatch info

Revision ID: e6020334d70f
Revises: e29415d976dd
Create Date: 2025-05-05 05:28:09.886255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e6020334d70f'
down_revision: Union[str, None] = 'e29415d976dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_info',
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('challan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('challan_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('eway_bill_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=True),
    sa.Column('customer_po_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('so_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('driver_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authorized_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dispatch_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inventryoutword_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch_info')
    # ### end Alembic commands ###
