"""add is_from_product

Revision ID: e96e136fd23f
Revises: 324d692832d7
Create Date: 2025-04-22 12:25:17.383015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96e136fd23f'
down_revision: Union[str, None] = '324d692832d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_stages', sa.Column('is_from_product', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_stages', 'is_from_product')
    # ### end Alembic commands ###
