"""add bank11

Revision ID: e9d635ca64db
Revises: b06644170040
Create Date: 2025-04-24 09:48:21.818699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d635ca64db'
down_revision: Union[str, None] = 'b06644170040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('config_bank_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_bank_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_bank_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('config_bank_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role_creation', 'config_bank_delete')
    op.drop_column('admin_role_creation', 'config_bank_edit')
    op.drop_column('admin_role_creation', 'config_bank_write')
    op.drop_column('admin_role_creation', 'config_bank_read')
    # ### end Alembic commands ###
