"""add all

Revision ID: ec52d1bea1bf
Revises: afb4c2832367
Create Date: 2025-04-19 07:37:55.247192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec52d1bea1bf'
down_revision: Union[str, None] = 'afb4c2832367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('employee_read', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('employee_write', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('employee_edit', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('employee_delete', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('config_read', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('config_write', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('config_edit', sa.Integer(), nullable=False))
    op.add_column('admin_role_creation', sa.Column('config_delete', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_role_creation', 'config_delete')
    op.drop_column('admin_role_creation', 'config_edit')
    op.drop_column('admin_role_creation', 'config_write')
    op.drop_column('admin_role_creation', 'config_read')
    op.drop_column('admin_role_creation', 'employee_delete')
    op.drop_column('admin_role_creation', 'employee_edit')
    op.drop_column('admin_role_creation', 'employee_write')
    op.drop_column('admin_role_creation', 'employee_read')
    # ### end Alembic commands ###
