"""87878

Revision ID: ecb6bbdf9f58
Revises: 4b2af80b21dc
Create Date: 2025-07-16 10:31:39.896684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'ecb6bbdf9f58'
down_revision: Union[str, None] = '4b2af80b21dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_read_status',
    sa.Column('notification_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('notification', sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('notification', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('notification', 'employee_id')
    op.drop_column('notification', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('employee_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('notification', 'created_by_type')
    op.drop_column('notification', 'created_by_id')
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_table('notification_read_status')
    # ### end Alembic commands ###
