"""approve by

Revision ID: ed637b1dbf75
Revises: a4cf8f41a141
Create Date: 2025-05-05 09:06:31.529592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed637b1dbf75'
down_revision: Union[str, None] = 'a4cf8f41a141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_outward', sa.Column('approve_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_outward', 'approve_by')
    # ### end Alembic commands ###
