"""grn

Revision ID: ee668c6a0b51
Revises: 70be39ac8350
Create Date: 2025-06-23 12:28:41.879794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee668c6a0b51'
down_revision: Union[str, None] = '70be39ac8350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_role_creation', sa.Column('purchase_grn_read', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('purchase_grn_write', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('purchase_grn_edit', sa.Integer(), nullable=True))
    op.add_column('admin_role_creation', sa.Column('purchase_grn_delete', sa.Integer(), nullable=True))
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'medical_file_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.drop_column('admin_role_creation', 'purchase_grn_delete')
    op.drop_column('admin_role_creation', 'purchase_grn_edit')
    op.drop_column('admin_role_creation', 'purchase_grn_write')
    op.drop_column('admin_role_creation', 'purchase_grn_read')
    # ### end Alembic commands ###
