"""comver_order_status33

Revision ID: ee7df1cdba26
Revises: a054725cfdaf
Create Date: 2025-05-05 11:58:17.953274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ee7df1cdba26'
down_revision: Union[str, None] = 'a054725cfdaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Store_sub_product_employee', sa.Column('parent_subproduct_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Store_sub_product_employee', 'parent_subproduct_id')
    # ### end Alembic commands ###
