"""company_name

Revision ID: efb0fb9d0ffb
Revises: d4f05a74fdd1
Create Date: 2025-05-16 10:36:49.967103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'efb0fb9d0ffb'
down_revision: Union[str, None] = 'd4f05a74fdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_vendor', sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_vendor', 'company_name')
    # ### end Alembic commands ###
