"""jkvfjklfkjv55

Revision ID: f1b29bd0a82a
Revises: 4b5eed9ebd34
Create Date: 2025-05-20 07:28:24.731590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f1b29bd0a82a'
down_revision: Union[str, None] = '4b5eed9ebd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_outward', sa.Column('dispatch_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('dispatch_admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('dispatch_created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('dispatch_approve_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('dispatch_approve_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('dispatch_updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_outward', 'dispatch_updated_at')
    op.drop_column('inventory_outward', 'dispatch_approve_by_id')
    op.drop_column('inventory_outward', 'dispatch_approve_by_type')
    op.drop_column('inventory_outward', 'dispatch_created_at')
    op.drop_column('inventory_outward', 'dispatch_admin_emp_id')
    op.drop_column('inventory_outward', 'dispatch_by_type')
    # ### end Alembic commands ###
