"""employe_name

Revision ID: f43e537d1989
Revises: 4bdd4f680b2d
Create Date: 2025-05-15 06:58:28.039730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f43e537d1989'
down_revision: Union[str, None] = '4bdd4f680b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_manager_order', sa.Column('hold_by_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_manager_order', 'hold_by_name')
    # ### end Alembic commands ###
