"""productDetails = []

Revision ID: f4c565049c49
Revises: 7d36f5a4a5e0
Create Date: 2025-06-11 06:18:29.810283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'f4c565049c49'
down_revision: Union[str, None] = '7d36f5a4a5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_files', 'image_path',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=4294967295),
               existing_nullable=True)
    op.add_column('late_mark', sa.Column('amount_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('late_mark', sa.Column('amount', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('late_mark', 'amount')
    op.drop_column('late_mark', 'amount_type')
    op.alter_column('employee_files', 'image_path',
               existing_type=sa.LargeBinary(length=4294967295),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
