"""add approve_by_id

Revision ID: f65646ab3cb2
Revises: da0dae0cafe7
Create Date: 2025-05-03 10:26:47.586060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f65646ab3cb2'
down_revision: Union[str, None] = 'da0dae0cafe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_outward', sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('admin_emp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('approve_by_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('inventory_outward', sa.Column('approve_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_outward', 'approve_by_id')
    op.drop_column('inventory_outward', 'approve_by_type')
    op.drop_column('inventory_outward', 'admin_emp_id')
    op.drop_column('inventory_outward', 'created_by_type')
    # ### end Alembic commands ###
