"""add purchase_order_id

Revision ID: f972ee0eddd3
Revises: f52a4cabb934
Create Date: 2025-04-30 11:22:40.444837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f972ee0eddd3'
down_revision: Union[str, None] = 'f52a4cabb934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_product', sa.Column('purchase_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_product', 'purchase_order_id')
    # ### end Alembic commands ###
